### ISSUE TITLE
小区和二手房运行会出现这个错误。

### ISSUE THREAD

**Issue by wukaiying** [jumper2014/lianjia-spider#10]
http://bj.lianjia.com/xiaoqu/dingfuzhuang/
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='bj.lianjia.com', port=443): Read timed out. (read timeout=10)
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/threadpool.py", line 158, in run
    result = request.callable(*request.args, **request.kwds)
  File "xiaoqu.py", line 34, in collect_xiaoqu_data
    xqs = get_xiaoqu_info(city_name, area_name)
  File "/Users/kaiyingwu/Downloads/lianjia-spider-master/lib/url/xiaoqu.py", line 101, in get_xiaoqu_info
    response = requests.get(page, timeout=10, headers=headers)
  File "/Library/Python/2.7/site-packages/requests-2.11.1-py2.7.egg/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.11.1-py2.7.egg/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.11.1-py2.7.egg/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.11.1-py2.7.egg/requests/sessions.py", line 617, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/Library/Python/2.7/site-packages/requests-2.11.1-py2.7.egg/requests/sessions.py", line 177, in resolve_redirects
    **adapter_kwargs
  File "/Library/Python/2.7/site-packages/requests-2.11.1-py2.7.egg/requests/sessions.py", line 628, in send
    r.content
  File "/Library/Python/2.7/site-packages/requests-2.11.1-py2.7.egg/requests/models.py", line 755, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/Library/Python/2.7/site-packages/requests-2.11.1-py2.7.egg/requests/models.py", line 683, in generate
    raise ConnectionError(e)

**Comment by jumper2014** [comment]
每次都会出这个错误么？
看上去是网络连接不好。

**Comment by jumper2014** [comment]
先关闭。
