### ISSUE TITLE
connection time out

### ISSUE THREAD

**Issue by ShawnNiu** [jumper2014/lianjia-spider#4]
运行ershou.py，提示
`HTTPSConnectionPool(host='yt.lianjia.com', port=443): Max retries exceeded with url: /xiaoqu/fushan (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x10a4308d0>, 'Connection to yt.lianjia.com timed out. (connect timeout=10)'))
fushan: Area list:  None
Traceback (most recent call last):
  File "ershou.py", line 135, in <module>
    areas.extend(areas_of_district)
TypeError: 'NoneType' object is not iterable`

是不是请求频繁被block了？

**Comment by jumper2014** [comment]
Https么？我代码里面貌似用的是http

**Comment by ShawnNiu** [comment]
改成https还是不行。试了两次的结果

```
`Today date is: 20180507
City: bj
Districts: ['dongcheng', 'xicheng', 'chaoyang', 'haidian', 'fengtai', 'shijingshan', 'tongzhou', 'changping', 'daxing', 'yizhuangkaifaqu', 'shunyi', 'fangshan', 'mentougou', 'pinggu', 'huairou', 'miyun', 'yanqing', 'yanjiao', 'xianghe']
dongcheng: Area list:  ['andingmen', 'anzhen1', 'chaoyangmenwai1', 'chaoyangmennei1', 'chongwenmen', 'dongdan', 'dongzhimen', 'dianmen', 'donghuashi', 'dongsi1', 'dengshikou', 'guangqumen', 'gongti', 'hepingli', 'jiaodaokou', 'jianguomenwai', 'jianguomennei', 'jinbaojie', 'liupukang', 'puhuangyu', 'qianmen', 'taoranting1', 'tiantan', 'xiluoyuan', 'xidan', 'yongdingmen', 'yangqiao1', 'zuoanmen1']
xicheng: Area list:  ['baizhifang1', 'caihuying', 'changchunjie', 'chongwenmen', 'chegongzhuang1', 'dianmen', 'deshengmen', 'fuchengmen', 'guanganmen', 'guanyuan', 'jinrongjie', 'liupukang', 'madian1', 'maliandao1', 'muxidi1', 'niujie', 'taoranting1', 'taipingqiao1', 'tianningsi1', 'xisi1', 'xuanwumen12', 'xizhimen1', 'xinjiekou2', 'xidan', 'yuetan', 'youanmennei11']
chaoyang: Area list:  ['andingmen', 'anzhen1', 'aolinpikegongyuan11', 'beiyuan2', 'beigongda', 'baiziwan', 'chengshousi1', 'changying', 'chaoyangmenwai1', 'cbd', 'chaoqing', 'chaoyanggongyuan', 'dongzhimen', 'dongba', 'dawanglu', 'dongdaqiao', 'dashanzi', 'dougezhuang', 'dingfuzhuang', 'fangzhuang1', 'fatou', 'guangqumen', 'gongti', 'gaobeidian', 'guozhan1', 'ganluyuan', 'guanzhuang', 'hepingli', 'huanlegu', 'huixinxijie', 'hongmiao', 'huaweiqiao', 'jianxiangqiao1', 'jiuxianqiao', 'jinsong', 'jianguomenwai', 'lishuiqiao1', 'madian1', 'nongzhanguan', 'nanshatan1', 'panjiayuan1', 'sanyuanqiao', 'shaoyaoju', 'shifoying', 'shilibao', 'shoudoujichang1', 'shuangjing', 'shilihe', 'shibalidian1', 'shuangqiao', 'sanlitun', 'sihui', 'tongzhoubeiyuan', 'tuanjiehu', 'taiyanggong', 'tianshuiyuan', 'wangjing', 'xibahe', 'yayuncun', 'yayuncunxiaoying', 'yansha1', 'zhongyangbieshuqu1', 'zhaoyangqita']
haidian: Area list:  ['aolinpikegongyuan11', 'anningzhuang1', 'baishiqiao1', 'beitaipingzhuang', 'changpingqita1', 'changwa', 'dinghuisi', 'erlizhuang', 'gongzhufen', 'ganjiakou', 'haidianqita1', 'haidianbeibuxinqu1', 'junbo1', 'liuliqiao1', 'mudanyuan', 'madian1', 'malianwa', 'qinghe11', 'suzhouqiao', 'shangdi1', 'shijicheng', 'sijiqing', 'shuangyushu', 'tiancun1', 'wudaokou', 'weigongcun', 'wukesong1', 'wanliu', 'wanshoulu1', 'xishan21', 'xisanqi1', 'xibeiwang', 'xueyuanlu1', 'xiaoxitian1', 'xizhimen1', 'xinjiekou2', 'xierqi1', 'yangzhuang1', 'yuquanlu11', 'yuanmingyuan', 'yiheyuan', 'zhichunlu', 'zaojunmiao', 'zhongguancun', 'zizhuqiao']
fengtai: Area list:  ['beidadi', 'beijingnanzhan1', 'chengshousi1', 'caoqiao', 'caihuying', 'dahongmen', 'fengtaiqita1', 'fangzhuang1', 'guanganmen', 'heyi', 'huaxiang', 'jiugong1', 'jiaomen', 'kejiyuanqu', 'kandanqiao', 'lize', 'liujiayao', 'lugouqiao1', 'liuliqiao1', 'muxiyuan1', 'majiabao', 'maliandao1', 'puhuangyu', 'qingta1', 'qilizhuang', 'songjiazhuang', 'shilihe', 'taipingqiao1', 'wulidian', 'xihongmen', 'xiluoyuan', 'xingong', 'yuegezhuang', 'yuquanying', 'youanmenwai', 'yangqiao1', 'zhaogongkou']
shijingshan: Area list:  ['bajiao1', 'chengzi', 'gucheng', 'laoshan1', 'lugu1', 'pingguoyuan1', 'shijingshanqita1', 'yangzhuang1', 'yuquanlu11']
tongzhou: Area list:  ['beiguan', 'guoyuan1', 'jiukeshu12', 'luyuan', 'liyuan', 'linheli', 'majuqiao1', 'qiaozhuang', 'shoudoujichang1', 'tongzhoubeiyuan', 'tongzhouqita11', 'wuyihuayuan', 'xinhuadajie', 'yizhuang1', 'yuqiao']
HTTPConnectionPool(host='bj.lianjia.com', port=80): Max retries exceeded with url: /xiaoqu/changping (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x10f275890>, 'Connection to bj.lianjia.com timed out. (connect timeout=10)'))
changping: Area list:  None
Traceback (most recent call last):
  File "ershou.py", line 133, in <module>
    areas.extend(areas_of_district)
TypeError: 'NoneType' object is not iterable`
```

```
`Today date is: 20180507
City: bj
Districts: ['dongcheng', 'xicheng', 'chaoyang', 'haidian', 'fengtai', 'shijingshan', 'tongzhou', 'changping', 'daxing', 'yizhuangkaifaqu', 'shunyi', 'fangshan', 'mentougou', 'pinggu', 'huairou', 'miyun', 'yanqing', 'yanjiao', 'xianghe']
HTTPSConnectionPool(host='bj.lianjia.com', port=443): Max retries exceeded with url: /xiaoqu/dongcheng/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x107372110>, 'Connection to bj.lianjia.com timed out. (connect timeout=10)'))
dongcheng: Area list:  None
Traceback (most recent call last):
  File "ershou.py", line 133, in <module>
    areas.extend(areas_of_district)
TypeError: 'NoneType' object is not iterable`
```

**Comment by jumper2014** [comment]
我的意思不是说改成HTTPS，你还是用HTTP跑吧。
1. 你是在虚拟机上跑么？虚拟机性能差，可能需要把线程数调低。
2. 确保你的网络连接是正常和稳定的。

**Comment by ShawnNiu** [comment]
本机跑
网络是联通100M光纤

**Comment by jumper2014** [comment]
哎，无法重现啊...
怀疑是你到lianjia网站的连接不太好。
